"""Album-tag association table

Revision ID: 0999d5de1ddf
Revises: d57841217b70
Create Date: 2021-02-20 18:46:10.513826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0999d5de1ddf'
down_revision = 'd57841217b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.UniqueConstraint('tag_id', 'album_id', name='unique_ids')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_tags')
    # ### end Alembic commands ###
