"""assert uniqeness in artist-tag assocation table

Revision ID: 1f6b79d93e47
Revises: a0c5fbff535c
Create Date: 2021-02-14 20:07:11.579209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6b79d93e47'
down_revision = 'a0c5fbff535c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_ids', 'artist_tags', ['tag_id', 'artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ids', 'artist_tags', type_='unique')
    # ### end Alembic commands ###
