"""artists table

Revision ID: 8a27921aa2b1
Revises: 93dad5868820
Create Date: 2021-02-13 17:55:08.657367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a27921aa2b1'
down_revision = '93dad5868820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_spotify_id'), 'artist', ['spotify_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_spotify_id'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
