"""Albums table

Revision ID: d57841217b70
Revises: 35bbb8772aed
Create Date: 2021-02-20 18:42:31.057488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57841217b70'
down_revision = '35bbb8772aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_spotify_id'), 'album', ['spotify_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_spotify_id'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
