"""Fix naming of unique constraints

Revision ID: ed74c7dc3f9a
Revises: 0999d5de1ddf
Create Date: 2021-02-26 21:44:12.812693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed74c7dc3f9a'
down_revision = '0999d5de1ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ids', 'album_tags', type_='unique')
    op.create_unique_constraint('unique_album_tag', 'album_tags', ['tag_id', 'album_id'])
    op.drop_constraint('unique_ids', 'artist_tags', type_='unique')
    op.create_unique_constraint('unique_artist_tag', 'artist_tags', ['tag_id', 'artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_artist_tag', 'artist_tags', type_='unique')
    op.create_unique_constraint('unique_ids', 'artist_tags', ['tag_id', 'artist_id'])
    op.drop_constraint('unique_album_tag', 'album_tags', type_='unique')
    op.create_unique_constraint('unique_ids', 'album_tags', ['tag_id', 'album_id'])
    # ### end Alembic commands ###
